배열의 연산

In [1]:
import numpy as np

벡터화 연산

In [2]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [3]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 7 ms


In [4]:
%%time
z = x + y

Wall time: 999 µs


In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [6]:
np.all(a == b)

False

In [7]:
np.all(a == c)

True

In [8]:
a = np.arange(1,11)
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

스칼라와 벡터/행렬의 곱셈

In [9]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [11]:
x =np.arange(12).reshape(3, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
# 브로드캐스팅

In [13]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [14]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [15]:
x+ y

array([1, 2, 3, 4, 5])

In [16]:
x + 1

array([1, 2, 3, 4, 5])

# 차원 축소

In [17]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [18]:
x.sum()

6

In [19]:
x.sum(axis=0)   # 열 합계

array([3, 3])

In [20]:
x.sum(axis=1)   # 행 합계

array([2, 4])

In [25]:
#연습 3.3.1
x = np.linspace(1.0,10.0,30).reshape(5,6)
x

array([[ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
         2.55172414],
       [ 2.86206897,  3.17241379,  3.48275862,  3.79310345,  4.10344828,
         4.4137931 ],
       [ 4.72413793,  5.03448276,  5.34482759,  5.65517241,  5.96551724,
         6.27586207],
       [ 6.5862069 ,  6.89655172,  7.20689655,  7.51724138,  7.82758621,
         8.13793103],
       [ 8.44827586,  8.75862069,  9.06896552,  9.37931034,  9.68965517,
        10.        ]])

In [24]:
x.max()

10.0

In [29]:
 y = x.sum(axis =1)
 y

array([10.65517241, 21.82758621, 33.        , 44.17241379, 55.34482759])

In [33]:
y.max()

55.3448275862069

In [35]:
y2 = x.sum(axis=0) /6
y2

array([3.93678161, 4.1954023 , 4.45402299, 4.71264368, 4.97126437,
       5.22988506])

In [36]:
y2.min()

3.936781609195402

sort

In [37]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [38]:
np.sort(a , axis= 1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [39]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [41]:
a.sort() #이건 값을 완전 바꿈

a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])