# 난수 발생과 카운팅

시드 설정하기

In [3]:
import numpy as np

In [5]:
np.random.rand(5)

array([0.05508444, 0.147635  , 0.74225114, 0.90573131, 0.3390126 ])

In [6]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [7]:
np.random.rand(5)

array([0.21695427, 0.27647714, 0.34331559, 0.86215894, 0.15669967])

In [8]:
np.random.seed(2020)
np.random.rand(5)   # 똑같이 나온다.

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

데이터의 순서 바꾸기

In [9]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.random.shuffle(x)  
# 자체 변환(in-place) 함수로 한 번 사용하면 변수의 값이 바뀌므로 사용에 주의해야 한다.
x

array([5, 7, 6, 4, 3, 1, 2, 8, 9, 0])

데이터 샘플링

In [11]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같다.비복원

array([4, 0, 1, 2, 3])

In [12]:
np.random.choice(5, 5, replace=True) 

array([4, 4, 0, 4, 1])

In [13]:
np.random.choice(5, 3, replace=False)  # 3개만 선택

array([2, 0, 4])

In [ ]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

난수 생성

In [14]:
np.random.rand(10)

array([0.02004476, 0.41216445, 0.50205984, 0.3550562 , 0.3862494 ,
       0.15672188, 0.40597552, 0.27212605, 0.81612241, 0.18040797])

In [15]:
np.random.randn(10)

array([ 1.06639311,  0.97750987,  0.84762002,  0.62842431, -2.04329806,
       -0.42138737, -0.0905073 ,  0.71308148,  0.09412645, -0.98878783])

In [17]:
#3.5.2
x = np.random.randn(250) * 100 + 10000
x[:10]

array([ 9867.24922761, 10112.82998064,  9953.54860673, 10097.00191983,
        9852.21546314,  9972.40744228, 10059.46974143, 10154.4646206 ,
        9942.04694836,  9965.60105781])

In [21]:
prices = []
price = 10000
for i in range(250):
    tomorrow = price * (1+ np.random.randn(1)/100.)
    price =tomorrow[0]
    prices.append(price)
prices[:10]

[10186.241237381135,
 10147.636794059074,
 10117.696623066025,
 9959.018311227532,
 10039.577889696553,
 10132.552214398698,
 10121.459145387846,
 10013.729804539835,
 9993.124476331583,
 10117.894859651267]

In [22]:
# 정수 데이터 카운팅
# unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력한다.

In [23]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [24]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [25]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [26]:
count

array([2, 2, 1], dtype=int64)