# 내적(inner product)

In [1]:
import numpy as np

In [2]:
x = np.arange(1,4).reshape(3,1)
x

array([[1],
       [2],
       [3]])

In [3]:
y = np.arange(4,7).reshape(3,1)
y

array([[4],
       [5],
       [6]])

In [4]:
x.shape,y.shape

((3, 1), (3, 1))

In [5]:
x.T.shape

(1, 3)

In [6]:
z = x.T @ y
z

array([[32]])

In [7]:
z.shape

(1, 1)

In [8]:
z[0,0]

32

In [9]:
np.dot(x.T,y)

array([[32]])

In [ ]:
#행렬과 행렬의 곱 2*3 3*2


In [10]:
p = np.array([100,80,50])
p

array([100,  80,  50])

In [11]:
n = np.array([3,4,5])
n

array([3, 4, 5])

In [17]:
price = p * n * 10000
price

array([3000000, 3200000, 2500000])

In [18]:
price.sum()

8700000

In [21]:
#선생님 풀이
x = np.array([3,4,5] )* 10000
x

array([30000, 40000, 50000])

In [22]:
#2.2.4
#1번
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = A @ B
C

array([[22, 28],
       [49, 64]])

In [23]:
#2번
c1 = B@A
c1

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [34]:
#3번
a = np.arrange(1,4)
b = np.array([[4,7],[5,8],[6,9]])
c =  a@b
c

AttributeError: module 'numpy' has no attribute 'arrange'

In [35]:
c1 = b*a
c1

array([[ 5, 12],
       [21, 32]])

In [37]:
#4번
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])
c = a@ b
c

array([[19, 22],
       [43, 50]])

In [36]:
c1 = b@a
c1

array([[23, 34],
       [31, 46]])

In [ ]:
#5번
