In [1]:
import pandas as pd 
import numpy as np

시리즈(Series)

In [2]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=["서울", "부산", "인천", "대구"])
s   #인덱싱이  0,1 뿐만 아니라..서울 부산도 가능

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [3]:
x =np.array([9904312, 3448737, 2890451, 2466052])
x

array([9904312, 3448737, 2890451, 2466052])

In [4]:
pd.Series(range(10,14))

0    10
1    11
2    12
3    13
dtype: int64

In [5]:
s.index , s.values

(Index(['서울', '부산', '인천', '대구'], dtype='object'),
 array([9904312, 3448737, 2890451, 2466052], dtype=int64))

In [6]:
s.name = "인구"
s.index.name = "도시"
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [7]:
s/1000000 #벡터화연산 가능

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

시리즈 인덱싱

In [8]:
s[1], s["부산"]

(3448737, 3448737)

In [9]:
s[["서울", "대구", "부산"]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [10]:
s[(250e4 < s) & (s < 500e4)]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [12]:
s[1:3]  # 데이터프레임에서는 3까지 포함

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [13]:
s["부산":"대구"] #대구까지 포함!!

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [14]:
s0 = pd.Series(range(3), index=["a", "b", "c"])
s0

a    0
b    1
c    2
dtype: int64

In [15]:
s0.a

0

시리즈와 딕셔너리 자료형

In [16]:
for k, v in s.items():
    print("%s = %d" % (k, v))  

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [17]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [18]:
#딕셔너리는 순서보장이 안된다.

In [19]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
               index=["부산", "서울", "인천", "대전"])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

인덱스 기반 연산

In [20]:
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [21]:
s.values - s2.values

array([ 6511121, -6182745,   258416,   975894], dtype=int64)

In [22]:
ds[ds.notnull()] #NaN이 아닌 값을 구하려면 notnull 메서드를 사용한다.
#대구,대전은 빠짐

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [23]:
#인구증가율
rs = (s - s2) / s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

데이터의 갱신, 추가, 삭제

In [26]:
rs["부산"] = 1.63
rs["대구"] = 1.41
del rs["서울"]
rs

부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64

연습문제 4.1.1

In [29]:
# 1
t2019 = pd.Series({"시츄":5,"비숑":8,"요크셔":4,"푸들":3 }, index=["시츄", "비숑", "요크셔","푸들"])
t2019.name = "강아지숫자2019"
t2019

시츄     5
비숑     8
요크셔    4
푸들     3
Name: 강아지숫자2019, dtype: int64

In [30]:
t2020 = pd.Series({"시츄":3,"비숑":12,"요크셔":2,"말티즈":5 }, index=["시츄", "비숑", "요크셔","말티즈"])
t2020.name = "강아지숫자2020"
t2020

시츄      3
비숑     12
요크셔     2
말티즈     5
Name: 강아지숫자2020, dtype: int64

In [31]:
# 증감
dp = t2020 -t2019
dp

말티즈    NaN
비숑     4.0
시츄    -2.0
요크셔   -2.0
푸들     NaN
dtype: float64

In [32]:
dp[dp.notnull()]

비숑     4.0
시츄    -2.0
요크셔   -2.0
dtype: float64

In [33]:
# 증감률
rp = (t2020 -t2019) / t2019 * 100
rp =rp[rp.notnull()]
rp

비숑     50.0
시츄    -40.0
요크셔   -50.0
dtype: float64

# 데이터프레임 클래스

데이터프레임 생성

In [34]:
data = {
    "지역" : ["수도권", "경상권", "수도권", "경상권"],
    "2015" : [9904312, 3448737, 2890451, 2466052],
    "2010" : [9631482, 3393191, 2632035, 2431774],
    "2005" : [9762546, 3512547, 2517680, 2456016],
    "2000" : [9853972, 3655437, 2466338, 2473990],
    "2010-2015 증가율" : [0.0283, 0.0163, 0.0982, 0.0141]
}
#columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [35]:
# 데이터프레임 : 공통 인덱스를 가지는 열 시리즈(column series)를 딕셔너리로 묶어놓은 것이라고 보는 것이 더 정확하다.

In [36]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [37]:
df.index.name = "도시"
df.columns.name = "특성"
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [38]:
df["2015"] 

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 2015, dtype: int64

In [39]:
df["2010"]

도시
서울    9631482
부산    3393191
인천    2632035
대구    2431774
Name: 2010, dtype: int64

In [41]:
(df["2015"] - df["2010"]) 

도시
서울    272830
부산     55546
인천    258416
대구     34278
dtype: int64

In [42]:
(df["2015"] - df["2010"]) / df["2010"] * 100

도시
서울    2.832690
부산    1.636984
인천    9.818107
대구    1.409588
dtype: float64

In [59]:
# 연습 문제 4.1.2

data = {
     "지역" : ["서울", "서울", "서울", "서울","서울"],
     "2019" : [5,8,4,3,0],
     "2020" : [3,12,2,0,5],
     "2020-2019증감수" : [-2,4,-2,-3,5],
     "2020-2019증감율" : (puppy["2020"] - puppy["2019"])/ puppy["2019"] * 100
     #"2020-2019증감율" : puppy["2020-2019증감수"]/ puppy["2019"] * 100
}
columns =["지역","2019","2020", "2020-2019증감수", "2020-2019증감율"]
index = ["시츄", "비숑", "요크셔","푸들","말티즈"]
puppy = pd.DataFrame(data, index=index, columns=columns)
puppy

지역  2019  2020  2020-2019증감수  2020-2019증감율
시츄   서울     5     3            -2         -40.0
비숑   서울     8    12             4          50.0
요크셔  서울     4     2            -2         -50.0
푸들   서울     3     0            -3        -100.0
말티즈  서울     0     5             5           inf

In [60]:
data = {
     "지역" : ["서울", "서울", "서울", "서울","서울"],
     "2019" : [5,8,4,3,0],
     "2020" : [3,12,2,0,5],
     "2020-2019증감수" : puppy["2020"] - puppy["2019"],
     "2020-2019증감율" : (puppy["2020"] - puppy["2019"])/ puppy["2019"] * 100
     #"2020-2019증감율" : puppy["2020-2019증감수"]/ puppy["2019"] * 100
}
columns =["지역","2019","2020", "2020-2019증감수", "2020-2019증감율"]
index = ["시츄", "비숑", "요크셔","푸들","말티즈"]
puppy = pd.DataFrame(data, index=index, columns=columns)
puppy

지역  2019  2020  2020-2019증감수  2020-2019증감율
시츄   서울     5     3            -2         -40.0
비숑   서울     8    12             4          50.0
요크셔  서울     4     2            -2         -50.0
푸들   서울     3     0            -3        -100.0
말티즈  서울     0     5             5           inf

In [51]:
data = {

     "지역" : ["서울", "서울", "서울", "서울","서울"],
     "2019" : [5,8,4,3,0],
     "2020" : [3,12,2,0,5],
     "2020-2019증감수" : [-2,4,-2,-3,5],
    
}
columns =["지역","2019","2020", "2020-2019증감수"]
index = ["시츄", "비숑", "요크셔","푸들","말티즈"]
puppy = pd.DataFrame(data, index=index, columns=columns)
puppy

지역  2019  2020  2020-2019증감수
시츄   서울     5     3            -2
비숑   서울     8    12             4
요크셔  서울     4     2            -2
푸들   서울     3     0            -3
말티즈  서울     0     5             5

In [57]:
 puppy["2020-2019증감율"] = (puppy["2020"] - puppy["2019"])/ puppy["2019"] * 100
 puppy

지역  2019  2020  2020-2019증감수  2020-2019증감율
시츄   서울     5     3            -2         -40.0
비숑   서울     8    12             4          50.0
요크셔  서울     4     2            -2         -50.0
푸들   서울     3     0            -3        -100.0
말티즈  서울     0     5             5           inf

In [61]:
# 열 인덱싱 : df["지역"] ,  df[["2010", "2015"]]
# 행 인덱싱 : df[:1] ,df["서울":"부산"]
# 개별인덱싱 : df["2015"]["서울"]

연습 문제 4.1.3

In [62]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [63]:
# 1
df["수학"]

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [65]:
#2
df[["국어","영어"]]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [67]:
#3
df["평균점수"] = df["국어"] /4
df

국어  영어  수학  평균점수
춘향  80  90  90  20.0
몽룡  90  70  60  22.5
향단  70  60  80  17.5
방자  30  40  70   7.5

In [68]:
del df["평균점수"]
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [73]:
df["과목평균점수"] = df.mean(axis=1).round(2) 
df

국어  영어  수학  과목평균점수
춘향  80  90  90   86.67
몽룡  90  70  60   73.33
향단  70  60  80   70.00
방자  30  40  70   46.67

In [ ]:
#df["과목평균점수"] = ((df["국어"] + df["영어"] +df["수학"])/3 ).round(2)

In [ ]:
#4 이거 다시보자
df["영어"]["방자"]

In [ ]:
#5
#df[:"춘향"].T

In [ ]:
#6
#df.T["향단"]