In [3]:
# 리스트와 어레이의 속도 비교
import numpy as np 
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]

In [4]:
%%time
for i in range(100) :
    sum(nu_list)

Wall time: 149 ms


In [5]:
%%time
for i in range(100) :
    np.sum(np_arr)

Wall time: 5 ms


1차원 배열 만들기

In [7]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
type(ar)

numpy.ndarray

In [9]:
ar.shape

(10,)

In [10]:
a = ([2 * i for i in range(1,11)])
a

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [11]:
2 *ar #리스트일 경우는 결과가 원값과 결과값 모두 출력

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [13]:
2*a +b

array([12, 24, 36])

In [14]:
a ==2 # 수식, 비교, 논리연산에 모두 가능

array([False,  True, False])

2차원 배열 만들기 (Metrix)

In [15]:
c = np.array([[0, 1, 2], [3, 4, 5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
c.shape

(2, 3)

In [18]:
d = np.array([[10,20,30,40],[50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [19]:
np.arange(10,90,10).reshape(2,-1)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

3차원 배열 만들기

In [20]:
e = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [21]:
e.shape, e.ndim

((2, 3, 4), 3)

배열 슬라이싱

In [22]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
a[:,1:3]

array([[1, 2],
       [5, 6]])

In [24]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]]) 
            # 행,열 모두 0부터 시작한다

In [30]:
m[1,2]

7

In [31]:
m[2,4]

14

In [33]:
m[1,1:3]

array([6, 7])

In [34]:
m[1:,2]

array([ 7, 12])

In [36]:
m[:2,3:5]

array([[3, 4],
       [8, 9]])

배열 인덱싱

In [37]:
a  = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [38]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [39]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx] 
# 어레이 자체를 인덱스로 주면...

array([11, 33, 55, 77, 99])

In [40]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
a[:, [True, False, False, True]] 
# 행은 모두다~ 열은 트루 폴스로

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [42]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [45]:
x[x% 4 == 1]

array([ 1,  5,  9, 13, 17])

In [51]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])