In [2]:
import numpy as np
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [3]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [4]:
x = np.array([1, 2, 3], dtype='float32')
x.dtype

dtype('float32')

Inf와 NaN

In [5]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

array([  0.,  inf, -inf,  nan])

In [6]:
a = np.zeros(5)
a   #기본이 실수다

array([0., 0., 0., 0., 0.])

In [7]:
a.dtype

dtype('float64')

In [8]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [9]:
c = np.zeros((2,5), dtype="int")
c

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones_like(c)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
g = np.empty((4, 3))
g

array([[8.12017116e-312, 2.86558075e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.82116729e-043],
       [5.58670705e-091, 1.72129232e+184, 2.36842258e+179],
       [2.69685671e+184, 6.48224659e+170, 5.82471487e+257]])

In [14]:
np.arange(3, 21, 2)  # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [16]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [17]:
np.log(np.logspace(0.1, 1, 10))

array([0.23025851, 0.46051702, 0.69077553, 0.92103404, 1.15129255,
       1.38155106, 1.61180957, 1.84206807, 2.07232658, 2.30258509])

전치 연산

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
A.T  # 헹과 열을 바꾼다

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
A.T @ A

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [22]:
A @ A.T

array([[14, 32],
       [32, 77]])

배열의 크기 변형

In [24]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
# 사용하는 원소의 갯수가 정해저 있기 때문에 reshape 명령의 형태 튜플의 원소 중 하나는 -1이라는 숫자로 대체할 수 있다. 
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a.flatten() # 다차원 배열을 다시 1차원으로 만들기

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [31]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [32]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [33]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

배열 연결

In [34]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [36]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [38]:
b1 = np.ones((2, 3))
b2 = np.zeros((3, 3))

In [39]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
#연습 3.2.1

In [42]:
x1 = np.zeros((3,3))
x1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
x2 = np.ones((3,2))
x2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [48]:
x3 = np.arange(10,160,10)
x4 = x3.reshape(3,-1)
x4

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [46]:
y1 = np.hstack([x1, x2])
y1

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [49]:
y2 = np.vstack([y1,x4])
y2

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [52]:
y = np.vstack([y2, y2])
y

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])