In [1]:
import numpy as np

1번

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2번

In [41]:
x = np.zeros(10)
x[4] =1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [55]:
np.eye(N=1, M=10, k=4)


array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

3번

In [28]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4번

In [29]:
 a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

5번

In [6]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6번

In [19]:
a = np.arange(0,5)
a[(a != 0) & (a != 3)]


array([1, 2, 4])

7번


In [20]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8번

In [21]:
a = np.random.rand(9).reshape(3,3)
a

array([[0.43089807, 0.41210567, 0.89253623],
       [0.8222443 , 0.94102331, 0.40215782],
       [0.08905434, 0.71662184, 0.41189701]])

9번

In [22]:
a.max(),a.min()

(0.941023308741876, 0.08905433907444071)

(array([0.57851332, 0.72180848, 0.40585773]),
 array([0.4473989 , 0.68991694, 0.56886369]))